version: '3'
services:

  sai-eth-indexer:
    build:
      context: ./saiEthIndexer
      dockerfile: Dockerfile
    ports:
      - "8817:8817"
    volumes:
        - ./saiEthIndexer/build/block.data:/srv/block.data
        - ./saiEthIndexer/build/config/config.json:/srv/config/config.json
        - ./saiEthIndexer/build/config/contracts.json:/srv/config/contracts.json
